/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package etaxgenerator.counterparty.create;

import etaxgenerator.counterparty.Counterparty;
import etaxgenerator.util.Util;

/**
 *
 * @author MojoMacW7
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form ETaxCounterpartyGeneratorUI
     */
    Builder builder = new Builder();
    PasteParser parser;
    public GUI() {
        initComponents();
        parser = new PasteParser(this, pasteField);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void refreshQueueCount(){
        queueCountLabel.setText("Count: " + String.valueOf(builder.size()));
    }
    public void load(Counterparty cp){
        if (cp == null){
            return;
        }
        npwpField.setText(cp.getFormattedNPWP());
        nameField.setText(cp.getCapsName());
        addressField.setText(cp.address);
        blockField.setText(cp.block);
        noField.setText(cp.no);
        rtField.setText(cp.rt);
        rwField.setText(cp.rw);
        kelurahanField.setText(cp.kelurahan);
        kecamatanField.setText(cp.kecamatan);
        cityField.setText(cp.city);
        provinceField.setText(cp.province);
        zipCodeField.setText(cp.zipCode);
        telephoneField.setText(cp.telephone);
    }
    public boolean check(){
        if(Util.isNullEmptyOrZero(npwpField.getText())){
            Util.showError("NPWP harus diisi dan tidak boleh nol", "Error");
            return false;
        }
        if(Util.isNullOrEmpty(nameField.getText())){
            Util.showError("Nama harus diisi", "Error");
            return false;
        }
        if(Util.isNullOrEmpty(addressField.getText())){
            Util.showError("Alamat harus diisi", "Error");
            return false;
        }
        
        return true;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel18 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        npwpField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        blockField = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        noField = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        rtField = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        rwField = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        kelurahanField = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        kecamatanField = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        provinceField = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        zipCodeField = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        telephoneField = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        parseButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        pasteField = new javax.swing.JTextArea();
        jPanel19 = new javax.swing.JPanel();
        deleteNPWPButton = new javax.swing.JButton();
        deleteNameButton = new javax.swing.JButton();
        findNameButton = new javax.swing.JButton();
        findNPWPButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        queueCountLabel = new java.awt.Label();
        clearQueueButton = new javax.swing.JButton();
        delPrevButton = new javax.swing.JButton();
        clearFormButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        generateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(290, 400));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel18.setLayout(new javax.swing.BoxLayout(jPanel18, javax.swing.BoxLayout.LINE_AXIS));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Lawan Transaksi");
        jLabel14.setToolTipText("");
        jPanel18.add(jLabel14);

        getContentPane().add(jPanel18);

        jPanel1.setMinimumSize(new java.awt.Dimension(132, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(260, 300));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        jLabel1.setText("NPWP");
        jLabel1.setMaximumSize(new java.awt.Dimension(60, 14));
        jLabel1.setMinimumSize(new java.awt.Dimension(60, 14));
        jLabel1.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel2.add(jLabel1);

        npwpField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npwpFieldActionPerformed(evt);
            }
        });
        jPanel2.add(npwpField);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.X_AXIS));

        jLabel2.setText("Nama");
        jLabel2.setMaximumSize(new java.awt.Dimension(60, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(60, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel3.add(jLabel2);

        nameField.setPreferredSize(new java.awt.Dimension(200, 20));
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        jPanel3.add(nameField);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.X_AXIS));

        jLabel3.setText("Alamat");
        jLabel3.setMaximumSize(new java.awt.Dimension(60, 14));
        jLabel3.setMinimumSize(new java.awt.Dimension(60, 14));
        jLabel3.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel4.add(jLabel3);

        addressField.setPreferredSize(new java.awt.Dimension(200, 20));
        addressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFieldActionPerformed(evt);
            }
        });
        jPanel4.add(addressField);

        jPanel1.add(jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(260, 20));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.X_AXIS));

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.X_AXIS));

        jLabel4.setText("Blok");
        jLabel4.setMaximumSize(new java.awt.Dimension(60, 14));
        jLabel4.setMinimumSize(new java.awt.Dimension(60, 14));
        jLabel4.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel6.add(jLabel4);

        blockField.setPreferredSize(new java.awt.Dimension(200, 20));
        blockField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockFieldActionPerformed(evt);
            }
        });
        jPanel6.add(blockField);

        jPanel5.add(jPanel6);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.X_AXIS));

        jLabel5.setText("No.");
        jLabel5.setMaximumSize(new java.awt.Dimension(60, 14));
        jLabel5.setMinimumSize(new java.awt.Dimension(60, 14));
        jLabel5.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel7.add(jLabel5);

        noField.setPreferredSize(new java.awt.Dimension(200, 20));
        noField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noFieldActionPerformed(evt);
            }
        });
        jPanel7.add(noField);

        jPanel5.add(jPanel7);

        jPanel1.add(jPanel5);

        jPanel8.setPreferredSize(new java.awt.Dimension(260, 20));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.X_AXIS));

        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.X_AXIS));

        jLabel6.setText("RT");
        jLabel6.setMaximumSize(new java.awt.Dimension(60, 14));
        jLabel6.setMinimumSize(new java.awt.Dimension(60, 14));
        jLabel6.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel9.add(jLabel6);

        rtField.setPreferredSize(new java.awt.Dimension(200, 20));
        rtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtFieldActionPerformed(evt);
            }
        });
        jPanel9.add(rtField);

        jPanel8.add(jPanel9);

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.X_AXIS));

        jLabel7.setText("RW");
        jLabel7.setMaximumSize(new java.awt.Dimension(60, 14));
        jLabel7.setMinimumSize(new java.awt.Dimension(60, 14));
        jLabel7.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel10.add(jLabel7);

        rwField.setPreferredSize(new java.awt.Dimension(200, 20));
        rwField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rwFieldActionPerformed(evt);
            }
        });
        jPanel10.add(rwField);

        jPanel8.add(jPanel10);

        jPanel1.add(jPanel8);

        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.X_AXIS));

        jLabel8.setText("Kelurahan");
        jLabel8.setMaximumSize(new java.awt.Dimension(60, 14));
        jLabel8.setMinimumSize(new java.awt.Dimension(60, 14));
        jLabel8.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel11.add(jLabel8);

        kelurahanField.setPreferredSize(new java.awt.Dimension(200, 20));
        kelurahanField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelurahanFieldActionPerformed(evt);
            }
        });
        jPanel11.add(kelurahanField);

        jPanel1.add(jPanel11);

        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.X_AXIS));

        jLabel9.setText("Kecamatan");
        jLabel9.setMaximumSize(new java.awt.Dimension(60, 14));
        jLabel9.setMinimumSize(new java.awt.Dimension(60, 14));
        jLabel9.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel12.add(jLabel9);

        kecamatanField.setPreferredSize(new java.awt.Dimension(200, 20));
        kecamatanField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kecamatanFieldActionPerformed(evt);
            }
        });
        jPanel12.add(kecamatanField);

        jPanel1.add(jPanel12);

        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.X_AXIS));

        jLabel10.setText("Kota");
        jLabel10.setMaximumSize(new java.awt.Dimension(60, 14));
        jLabel10.setMinimumSize(new java.awt.Dimension(60, 14));
        jLabel10.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel13.add(jLabel10);

        cityField.setPreferredSize(new java.awt.Dimension(200, 20));
        cityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityFieldActionPerformed(evt);
            }
        });
        jPanel13.add(cityField);

        jPanel1.add(jPanel13);

        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.X_AXIS));

        jLabel11.setText("Provinsi");
        jLabel11.setMaximumSize(new java.awt.Dimension(60, 14));
        jLabel11.setMinimumSize(new java.awt.Dimension(60, 14));
        jLabel11.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel14.add(jLabel11);

        provinceField.setPreferredSize(new java.awt.Dimension(200, 20));
        provinceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinceFieldActionPerformed(evt);
            }
        });
        jPanel14.add(provinceField);

        jPanel1.add(jPanel14);

        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.X_AXIS));

        jLabel12.setText("Kode Pos");
        jLabel12.setMaximumSize(new java.awt.Dimension(60, 14));
        jLabel12.setMinimumSize(new java.awt.Dimension(60, 14));
        jLabel12.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel15.add(jLabel12);

        zipCodeField.setPreferredSize(new java.awt.Dimension(200, 20));
        zipCodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipCodeFieldActionPerformed(evt);
            }
        });
        jPanel15.add(zipCodeField);

        jPanel1.add(jPanel15);

        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.X_AXIS));

        jLabel13.setText("No. Telp");
        jLabel13.setMaximumSize(new java.awt.Dimension(60, 14));
        jLabel13.setMinimumSize(new java.awt.Dimension(60, 14));
        jLabel13.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel16.add(jLabel13);

        telephoneField.setPreferredSize(new java.awt.Dimension(200, 20));
        telephoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephoneFieldActionPerformed(evt);
            }
        });
        jPanel16.add(telephoneField);

        jPanel1.add(jPanel16);

        getContentPane().add(jPanel1);

        jPanel20.setLayout(new javax.swing.BoxLayout(jPanel20, javax.swing.BoxLayout.LINE_AXIS));

        jLabel15.setText("Paste Excel");
        jLabel15.setPreferredSize(new java.awt.Dimension(80, 14));
        jPanel20.add(jLabel15);

        parseButton.setText("Parse");
        parseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parseButtonActionPerformed(evt);
            }
        });
        jPanel20.add(parseButton);

        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton1);

        pasteField.setColumns(20);
        pasteField.setRows(5);
        jScrollPane2.setViewportView(pasteField);

        jPanel20.add(jScrollPane2);

        getContentPane().add(jPanel20);

        jPanel19.setLayout(new javax.swing.BoxLayout(jPanel19, javax.swing.BoxLayout.LINE_AXIS));

        deleteNPWPButton.setText("Delete By NPWP");
        deleteNPWPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteNPWPButtonActionPerformed(evt);
            }
        });
        jPanel19.add(deleteNPWPButton);

        deleteNameButton.setText("Delete By Name");
        deleteNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteNameButtonActionPerformed(evt);
            }
        });
        jPanel19.add(deleteNameButton);

        findNameButton.setText("Find By Name");
        findNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findNameButtonActionPerformed(evt);
            }
        });
        jPanel19.add(findNameButton);

        findNPWPButton.setText("Find By NPWP");
        findNPWPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findNPWPButtonActionPerformed(evt);
            }
        });
        jPanel19.add(findNPWPButton);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel19.add(saveButton);

        getContentPane().add(jPanel19);

        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.LINE_AXIS));

        queueCountLabel.setText("Count: 0");
        jPanel17.add(queueCountLabel);

        clearQueueButton.setText("Clear Queue");
        clearQueueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearQueueButtonActionPerformed(evt);
            }
        });
        jPanel17.add(clearQueueButton);

        delPrevButton.setText("Del Prev");
        delPrevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delPrevButtonActionPerformed(evt);
            }
        });
        jPanel17.add(delPrevButton);

        clearFormButton.setText("Clear Form");
        clearFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFormButtonActionPerformed(evt);
            }
        });
        jPanel17.add(clearFormButton);

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel17.add(addButton);

        generateButton.setText("Generate");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });
        jPanel17.add(generateButton);

        getContentPane().add(jPanel17);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void npwpFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npwpFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_npwpFieldActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void addressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressFieldActionPerformed

    private void blockFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blockFieldActionPerformed

    private void noFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noFieldActionPerformed

    private void rtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rtFieldActionPerformed

    private void rwFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rwFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rwFieldActionPerformed

    private void kelurahanFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelurahanFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelurahanFieldActionPerformed

    private void kecamatanFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kecamatanFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kecamatanFieldActionPerformed

    private void cityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityFieldActionPerformed

    private void provinceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provinceFieldActionPerformed

    private void zipCodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipCodeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipCodeFieldActionPerformed

    private void telephoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneFieldActionPerformed

    private void clearQueueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearQueueButtonActionPerformed
        // TODO add your handling code here:
        if(Util.askConfirmation("Are you sure you want to clear the export queue?", "Confirmation")){
            builder.clear();
            refreshQueueCount();
        }
    }//GEN-LAST:event_clearQueueButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        if(add()){
            refreshQueueCount();
            Util.showMessage("Lawan transaksi berhasil dimasukkan ke export queue", "Success");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        // TODO add your handling code here:
        generate();
    }//GEN-LAST:event_generateButtonActionPerformed

    private void clearFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFormButtonActionPerformed
        // TODO add your handling code here:
        if(Util.askConfirmation("Are you sure you want to clear the form?", "Confirmation")){
            clearForm();
        }
    }//GEN-LAST:event_clearFormButtonActionPerformed

    private void delPrevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delPrevButtonActionPerformed
        // TODO add your handling code here:
        if(Util.askConfirmation("Are you sure you want to delete the previous export queue entry?", "Confirmation")){
            builder.deleteLast();
            refreshQueueCount();
        }
    }//GEN-LAST:event_delPrevButtonActionPerformed

    private void deleteNPWPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteNPWPButtonActionPerformed
        // TODO add your handling code here:
        String npwp = npwpField.getText().trim();
        if(Util.askConfirmation(String.format("Apa anda benar benar ingin menghapus lawan transaksi dengan NPWP \"%s\"?", npwp), "Konfirmasi")){
            boolean del = etaxgenerator.counterparty.Database.getInstance().removeByNPWP(Util.numericOnly(npwp));
            if (del){
                Util.showMessage(String.format("Lawan transaksi dengan NPWP \"%s\" telah dihapus.", npwp), "Success");
            }else{
                Util.showError(String.format("Lawan transaksi dengan NPWP \"%s\" tidak ditemukan.", npwp), "Failed");
            }
        }
    }//GEN-LAST:event_deleteNPWPButtonActionPerformed

    private void deleteNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteNameButtonActionPerformed
        // TODO add your handling code here:
        String name = nameField.getText().trim();
        if(Util.askConfirmation(String.format("Apa anda benar benar ingin menghapus lawan transaksi dengan nama \"%s\"?", name), "Konfirmasi")){
            boolean del = etaxgenerator.counterparty.Database.getInstance().removeByName(Counterparty.getCapsName(name));
            if (del){
                Util.showMessage(String.format("Lawan transaksi dengan nama \"%s\" telah dihapus.", name), "Success");
            }else{
                Util.showError(String.format("Lawan transaksi dengan nama \"%s\" tidak ditemukan.", name), "Failed");
            }
        }
    }//GEN-LAST:event_deleteNameButtonActionPerformed

    private void findNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findNameButtonActionPerformed
        // TODO add your handling code here:
        String name = nameField.getText().trim();
        Counterparty cp = etaxgenerator.counterparty.Database.getInstance().findByName(Counterparty.getCapsName(name));
        if (cp == null){
            Util.showError(String.format("Lawan transaksi dengan nama \"%s\" tidak ditemukan.", name), "Failed");
        }else{
            load(cp);
        }
    }//GEN-LAST:event_findNameButtonActionPerformed

    private void findNPWPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findNPWPButtonActionPerformed
        // TODO add your handling code here:
        String npwp = npwpField.getText().trim();
        Counterparty cp = etaxgenerator.counterparty.Database.getInstance().findByNPWP(Util.numericOnly(npwp));
        if (cp == null){
            Util.showError(String.format("Lawan transaksi dengan NPWP \"%s\" tidak ditemukan.", npwp), "Failed");
        }else{
            load(cp);
        }
    }//GEN-LAST:event_findNPWPButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        Counterparty cp = read();
        if(!etaxgenerator.counterparty.Database.getInstance().insertIfNotExists(cp) && Util.askConfirmation("Do you want to replace?", "Lawan transaksi sudah terdaftar")){
            etaxgenerator.counterparty.Database.getInstance().insertOrUpdate(cp);
        }
        Util.showMessage(String.format("Counterparty \"%s\" and \"%s\" has been successfully saved into database", cp.npwp, cp.name), "Success");
    }//GEN-LAST:event_saveButtonActionPerformed

    private void parseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parseButtonActionPerformed
        // TODO add your handling code here:
        parser.parse(pasteField.getText());
    }//GEN-LAST:event_parseButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pasteField.setText(parser.generate());
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void clearForm(){
        npwpField.setText("");
        nameField.setText("");
        addressField.setText("");
        blockField.setText("");
        noField.setText("");
        rtField.setText("");
        rwField.setText("");
        kelurahanField.setText("");
        kecamatanField.setText("");
        cityField.setText("");
        provinceField.setText("");
        zipCodeField.setText("");
        telephoneField.setText("");
        pasteField.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    
    public Counterparty read(){
        Counterparty cp = new Counterparty();
        cp.npwp = npwpField.getText().trim();
        cp.name = nameField.getText().trim();
        cp.address = addressField.getText().trim();
        cp.block = blockField.getText().trim();
        cp.no = noField.getText().trim();
        cp.rt = rtField.getText().trim();
        cp.rw = rwField.getText().trim();
        cp.kelurahan = kelurahanField.getText().trim();
        cp.kecamatan = kecamatanField.getText().trim();
        cp.city =cityField.getText().trim();
        cp.province = provinceField.getText().trim();
        cp.zipCode = zipCodeField.getText().trim();
        cp.telephone = telephoneField.getText().trim();
        return cp;
    }
    
    public boolean add(){
        if(!check()){
            return false;
        }
        Counterparty cp = read();
        builder.add(cp);
        refreshQueueCount();
        return true;
    }
    
    public void generate(){
        int x = builder.size();
        if(builder.size() == 0){
            if(!add()){
                return;
            }
        }
        int[] o = builder.export();
        refreshQueueCount();
        Util.showMessage(String.format("%d/%d Lawan transaksi berhasil export.\n%d Lawan transaksi yang sebelunya tidak ada berhasil dimasukkan ke database", o[0], x, o[1]), "Success");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    public javax.swing.JTextField addressField;
    public javax.swing.JTextField blockField;
    public javax.swing.JTextField cityField;
    private javax.swing.JButton clearFormButton;
    private javax.swing.JButton clearQueueButton;
    private javax.swing.JButton delPrevButton;
    private javax.swing.JButton deleteNPWPButton;
    private javax.swing.JButton deleteNameButton;
    private javax.swing.JButton findNPWPButton;
    private javax.swing.JButton findNameButton;
    private javax.swing.JButton generateButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField kecamatanField;
    public javax.swing.JTextField kelurahanField;
    public javax.swing.JTextField nameField;
    public javax.swing.JTextField noField;
    public javax.swing.JTextField npwpField;
    private javax.swing.JButton parseButton;
    public javax.swing.JTextArea pasteField;
    public javax.swing.JTextField provinceField;
    private java.awt.Label queueCountLabel;
    public javax.swing.JTextField rtField;
    public javax.swing.JTextField rwField;
    private javax.swing.JButton saveButton;
    public javax.swing.JTextField telephoneField;
    public javax.swing.JTextField zipCodeField;
    // End of variables declaration//GEN-END:variables
}
